### ISSUE TITLE
In TracerouteWithPing.java, the arraylist traces is always empty.

### ISSUE THREAD

**Issue by liuyang1213** [olivierg13/TraceroutePing#2]
Hello! Thank you for this library, and it helps a lot in my learning process.
However, when I tried to run it as an application, I found that the list is always filled up to 40 rows, even if the route is shorter. 
If my understanding is not wrong, when traceroute to a host that can be reached with a ttl smaller than MAX_TTL, the ping should stop at the point that it is reached. For example, if the example.com can be reached with ttl 10, then the only 10+1 = 11 pings should be executed. However, currently it still executes ping for MAX_TTL times since the condition in line 266 will never be satisfied (traces is always empty). Did you forget to add the trace declared in line 160 into traces? Even so, in my opinion, the traces is not that useful, you can just store the "latest trace" and check whether its ip is the expected destination. 
:)

**Comment by liuyang1213** [comment]
Besides, I think there is a bug when route is successfully traced but the ping to the input ip fails, since the time cannot be correctly parsed from result.

**Comment by liuyang1213** [comment]
Besides, I think elapsedTime should be 0 if the ping fails :)

**Comment by oliveeyay** [comment]
Thanks for the debugging and the pull request. It's merged! :)
