### ISSUE TITLE
Trace route on data network

### ISSUE THREAD

**Issue by ashudb70** [olivierg13/TraceroutePing#4]
Traceroute shows only on WiFi network and not on data network 
That is the number of hops are shown only if connected to WiFi and not on data network how do i fix it?

**Comment by oliveeyay** [comment]
Sorry it's working for me on data network. Maybe your ISP is preventing you from collecting IP addresses after their routers?

**Comment by ashudb70** [comment]
hi ur project is very useful, how can i show *** in case isp is preventing as it occurs in normal cmd promt atleast i will come to know number of hops it took to reach that IP
